name: compiled_mirrors
description: Mirrors-free reflection for Dart objects.
dependencies:
  analyzer: any
  build: any
  build_runner: any
  build_test: any
  quiver: any
dev_dependencies:
  test: any
